spring:
  activiti:
    #?????????
    #1.flase?????activiti????????????????????????????????????
    #2.true? activiti????????????????????????????
    #3.create_drop? ?activiti??????????????????????????????
    #4.drop-create? ?activiti?????????????????????????????
    database-schema-update: true
    #activiti7????????????????
    db-history-used: true
    #?????? ?????????none, activity, audit, full
    #none???????????????????????????????
    #activity?????none?????????????????????
    #audit??activity??????????????????????????audit?history?????
    #full??????????????????audit???????????????????????????????????
    history-level: full
    # =============================
    #????????????? ????????????
    check-process-definitions: true
    # asyncExecutorActivate??activiti??????????AsyncExecutor,???true-???????false-??
    async-executor-activate: true
  #??????????,????????
  #      process-definition-location-prefix: classpath:/processes/holliday/
  #process-definition-location-suffixes: #??????
  #  - **.bpmn20.xml
  #  - **.bpmn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&useSSL=true
    username: root
    password: Joker217

server:
  port: 8080
