server:
  port: 8080

spring:
  datasource:
    blog:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: Joker217
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      jdbc-url: jdbc:mysql://localhost:3306/white_jotter
      username: root
      password: Joker217
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
