
spring:
  data:
    # Redis ??
    redis:
      # Redis ?????
      host: 127.0.0.1
      # ?????
      port: 6379
      # ??????0 - 15?
      database: 0
      # ??????????
      timeout: 10000
      # lettuce ??
      lettuce:
        pool:
          # ?????(??????????) ??? 8
          max-active: 10
          # ????????(??????????) ??? -1 ms
          max-wait: -1
          # ?????? ??? 8
          max-idle: 5
          # ?????? ??? 0
          min-idle: 0
      password: 123456
